import '@/app/globals.css'
import { cn } from '@/lib/utils'
import { Inter as FontSans } from "next/font/google"
import type { Metadata } from "next";
import { Header } from '@/components/Header';

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased bg-gray-100",
          fontSans.variable
        )}
      >
        <Header/>
        {children}
      </body>
    </html>
  )
}
